apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::682354852696:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1PZQ1P4Y7TGFB
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-02T21:33:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "918"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ef97bb11-5ddc-4f75-9ebd-d8366821f098
